SUPABASE_URL_ENV = "SUPABASE_URL"
SUPABASE_KEY_ENV = "SUPABASE_KEY"

RECIPES_TABLE = "recipes"
CATEGORIES_TABLE = "categories"

RECIPES_SELECT_COLUMNS = "id, area, category, image_url"

UNKNOWN_AREA = "Unknown"
ALL_CATEGORY_TYPE = "*"
CLASSICS_SUFFIX = "classics"
SPECIALS_SUFFIX = "specials"

EMPTY_SUBTITLE = ""
EMPTY_IMAGE_URL = ""

DELETE_ALL_SENTINEL_ID = "00000000-0000-0000-0000-000000000000"

SMALL_AREA_RECIPE_THRESHOLD = 23
STRONG_CATEGORY_RECIPE_THRESHOLD = 5

STARS_MULTIPLIER = 3
ROUNDING_BASE = 5

